### ISSUE TITLE
Use soft tabs in generated BUCK files.

### ISSUE THREAD

**Issue by ragunathjawahar** [OkBuilds/OkBuck#143]
The generated **BUCK** files currently use hard tabs for formatting instead of soft tabs. It's visually distracting when the IDE's show whitespace chars option is enabled.

![whitespace](https://cloud.githubusercontent.com/assets/1141970/17330107/1a6999c8-58e3-11e6-88a3-a560f95e8815.png)

**Comment by kageiit** [comment]
These are generated files. You can turn off that option in your ide for now. Will probably handle this at a later time. Not really a high priority sorry
