### ISSUE TITLE
Gradle 3.0 and android tools gralde not working 

### ISSUE THREAD

**Issue by eggcaker** [OkBuilds/OkBuck#175]
Just setup OkBuck following README, and ran `./gradlew okbuck`, lot of files generated, but cannot build when run `buck targets` , got error says cannot resolve LIBRARY_PROJECT:src_release .  

LIBRARY_PROJECT is a locale library dependency. 

is it okbuck support latest version of gradle  now ?

**Comment by kageiit** [comment]
Can you be more elaborate?

What version of the android gradle plugin are you using?

We dont recommend running buck directly. Please use the buck wrapper (`buckw`) as specified in the readme

**Comment by eggcaker** [comment]
the latest version  of gralde (3.0 ) and android tools gradle: 2.2.0 with buckw

**Comment by kageiit** [comment]
The later version of gradle is 3.1 and it works fine with 2.2.0 . Please post provide a test/repro project that can reliably reproduce this issue

**Comment by eggcaker** [comment]
it's a closed source project . Just tried the latest gradle (3.1) with 2.2.0. same error.  maybe it's just my local android library configure not with standard way. but with gradle it's all works.  Close for now.
