### ISSUE TITLE
Not support Android Data Binding now

### ISSUE THREAD

**Issue by archmages** [OkBuilds/OkBuck#55]

**Comment by Piasy** [comment]
Yes, because BUCK not support it now.

**Comment by kageiit** [comment]
Nothing we can do here

**Comment by borut123** [comment]
any news about this?

**Comment by kageiit** [comment]
Databinding is tied very closely into the android gradle plugin at the moment. @borut123 please open a separate issue so we can track whats needed to support the feature. Thanks!
