### ISSUE TITLE
Provided dependencies not picked up by buck

### ISSUE THREAD

**Issue by nbonavia** [OkBuilds/OkBuck#62]
Hi,

I don't know if this is a buck or okbuck issue, but when I use project lombok or hrisey in my android project, they are only used during compilation. They are typically defined as shown below: -

dependencies {
    provided 'pl.mg6.hrisey:hrisey:0.3.+'
}

Unfortunately when dependencies are set as provided, they give a compilation error when running buck install. Could it be a missing configuration during okbuck generation?

**Comment by Piasy** [comment]
Yes OkBuck won't generate BUCK rule dependency for provided configuration, and of course OkBuck could. But I don't understand why provided configuration (compile time dependency) is needed more than apt (annotation processor) usage. Could you please give me more explanation?

**Comment by kageiit** [comment]
Try to get around this by using the apt configuration instead of provided

https://bitbucket.org/hvisser/android-apt

**Comment by Piasy** [comment]
@kageiit OkBuck could recognize `provided` and `apt` dependencies, but didn't make them part of module library compile dependencies. 

The problem is I don't understand why provided configuration (compile time dependency) is needed more than apt (annotation processor) usage.

**Comment by kageiit** [comment]
@Piasy There are valid cases where you would want to use provided dependencies outside the scope of annotation processing.

An example would be a java library that needs to use Parcelable, but does not want to be tied to be an aar. Another example is Robolectric test framework.

In that case, provided will be used to compile the jar and the parcelable classes are actually provided by the android os.

In the issue pointed out here, hrisey is a library that generates Parcelable classes. Which means the provided android dependency needs to be present for compile, but not be bundled into the final target.

**Comment by Piasy** [comment]
@kageiit Thanks for your reply!

But I don't know whether BUCK support this kind of dependency, I mean, if we put a gradle `provided` or `apt` scoped dependency into a `android_library` or `java_library` rule's deps list, will BUCK only use it for compile purpose? or BUCK will bundle it into the final target?

**Comment by kageiit** [comment]
You can use the solution preferred by buck authors from here: https://groups.google.com/forum/#!topic/buck-build/pz8NZsAeYdw

**Comment by kageiit** [comment]
> will BUCK only use it for compile purpose? or BUCK will bundle it into the final target?

confirmed with buck team that it is only used for compile since dependencies are not exported by default from a target
