### ISSUE TITLE
there is a problem when buck install

### ISSUE THREAD

**Issue by sherryein** [OkBuilds/OkBuck#67]
trouble processing "java/io/DataInputStream.class":

Ill-advised or mistaken usage of a core class (java.* or javax.*)
when not building a core library.

This is often due to inadvertently including a core library file
in your application's project, when using an IDE (such as
Eclipse). If you are sure you're not intentionally defining a
core class, then this is the most likely explanation of what's
going on.

However, you might actually be trying to define a class in a core
namespace, the source of which you may have taken, for example,
from a non-Android virtual machine project. This will most
assuredly not work. At a minimum, it jeopardizes the
compatibility of your app with future versions of the platform.
It is also often of questionable legality.
...

1 error; aborting

**Comment by Piasy** [comment]
I think it's not problem of OkBuck, but Android build tool, references:
http://stackoverflow.com/questions/7661559/ill-advised-or-mistaken-usage-of-a-core-class-java-or-javax-when-not-build
http://stackoverflow.com/questions/18266853/attempted-to-fix-androids-ill-advised-or-mistaken-usage-of-a-core-class-went-b
http://blog.csdn.net/cyj5366/article/details/9629809

**Comment by kageiit** [comment]
This error is thrown by dx, when buck tries to invoke dx to create the classes.dex

do a `./gradlew dependencies` and see if you have any packages with javax.* in the output. You may want to remove them via gradle dependency exclude rules to get buck to build
